# Generated by Django 5.1.1 on 2024-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correoCliente',
            field=models.EmailField(blank=True, help_text='Ingrese el Correo del Cliente', max_length=100, null=True),
        ),
    ]
